export const roleKeypoints = {
  full_stack_developer: {
    title: 'Full Stack Developer',
    requiredSkills: [
      'HTML',
      'CSS',
      'JavaScript',
      'React',
      'Node.js',
      'Express.js',
      'MongoDB',
      'REST API',
      'Git',
    ],
    goodToHave: ['TypeScript', 'Docker', 'AWS', 'Testing', 'CI/CD'],
  },
  frontend_developer: {
    title: 'Frontend Developer',
    requiredSkills: [
      'HTML',
      'CSS',
      'JavaScript',
      'React',
      'Responsive Design',
      'REST API',
      'Git',
      'Accessibility',
    ],
    goodToHave: ['TypeScript', 'Next.js', 'Testing', 'Tailwind CSS', 'Redux'],
  },
  backend_developer: {
    title: 'Backend Developer',
    requiredSkills: [
      'Node.js',
      'Express.js',
      'REST API',
      'MongoDB',
      'SQL',
      'Authentication',
      'Git',
      'API Security',
    ],
    goodToHave: ['Docker', 'AWS', 'Testing', 'CI/CD', 'Microservices'],
  },
  data_analyst: {
    title: 'Data Analyst',
    requiredSkills: [
      'Excel',
      'SQL',
      'Python',
      'Data Visualization',
      'Statistics',
      'Power BI',
      'Data Cleaning',
      'Reporting',
    ],
    goodToHave: ['Tableau', 'Pandas', 'NumPy', 'Machine Learning', 'Business Intelligence'],
  },
  ui_ux_designer: {
    title: 'UI/UX Designer',
    requiredSkills: [
      'Figma',
      'Wireframing',
      'Prototyping',
      'User Research',
      'User Flows',
      'Usability Testing',
      'Design Systems',
      'Responsive Design',
    ],
    goodToHave: ['Accessibility', 'HTML', 'CSS', 'Adobe XD', 'Product Thinking'],
  },
};
